default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: viversaude_development

test:
  <<: *default
  database: viversaude_test

production:
  <<: *default
  database: viversaude_production
  username: viversaude
  password: <%= ENV['viversaude_DATABASE_PASSWORD'] %>
